name = "mail-portal"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "siip.biz.id"
APP_BASE_URL = "https://mail-portal.siip.biz.id"
DEFAULT_ALIAS_LIMIT = "3"
SESSION_TTL_SECONDS = "1209600"
RESET_TTL_SECONDS = "3600"

[[d1_databases]]
binding = "DB"
database_name = "mail_portal"
database_id = "c9186742-6e38-4ffe-8dae-ad121e656e0e"
